import { useState, useRef, useEffect } from "react";
import { Link } from "react-router-dom";
import ThemeSelector from "../../components/ThemeSelector";
import { 
    FiFileText, FiCalendar, FiDownload, FiClock, FiSettings,
    FiPlus, FiMoreVertical, FiArrowRight, FiActivity, FiUsers, FiCreditCard, FiServer, FiX
} from "react-icons/fi";
import { BiBuildingHouse } from "react-icons/bi";
import * as XLSX from "xlsx";
import { jsPDF } from "jspdf";
import toast from "react-hot-toast";
import "./Reports.css";

function Reports() {
    const [startDate, setStartDate] = useState("2025-08-01");
    const [endDate, setEndDate] = useState("2026-08-31");
    const [showModal, setShowModal] = useState(false);
    const [newReport, setNewReport] = useState({ name: '', category: 'Institute Reports', type: 'Summary', format: 'PDF' });
    const [actionMenuOpen, setActionMenuOpen] = useState(null);
    const menuRef = useRef(null);

    useEffect(() => {
        const handleClickOutside = (event) => {
            if (menuRef.current && !menuRef.current.contains(event.target)) {
                setActionMenuOpen(null);
            }
        };
        document.addEventListener("mousedown", handleClickOutside);
        return () => document.removeEventListener("mousedown", handleClickOutside);
    }, []);

    const handleDownload = (report) => {
        toast.loading(`Generating ${report.format} for ${report.name}...`, { id: 'export' });
        
        setTimeout(() => {
            if (report.format === 'Excel') {
                const ws = XLSX.utils.json_to_sheet([report]);
                const wb = XLSX.utils.book_new();
                XLSX.utils.book_append_sheet(wb, ws, "Report");
                XLSX.writeFile(wb, `${report.name.replace(/\s+/g, '_')}.xlsx`);
            } else {
                const doc = new jsPDF();
                doc.setFontSize(20);
                doc.text(report.name, 14, 22);
                doc.setFontSize(12);
                doc.text(`Category: ${report.category}`, 14, 32);
                doc.text(`Type: ${report.type}`, 14, 40);
                doc.text(`Date Range: ${report.dateRange}`, 14, 48);
                doc.text(`Generated By: ${report.generatedBy}`, 14, 56);
                doc.text(`Generated On: ${report.generatedOn}`, 14, 64);
                doc.save(`${report.name.replace(/\s+/g, '_')}.pdf`);
            }
            toast.success(`${report.format} generated successfully!`, { id: 'export' });
        }, 800);
    };

    const handleGenerate = (e) => {
        e.preventDefault();
        const generatedReport = {
            id: Date.now(),
            name: newReport.name || "Custom Report",
            desc: "Custom generated report",
            icon: <FiFileText />,
            iconClass: "icon-purple",
            category: newReport.category,
            catBadge: "purple",
            type: newReport.type,
            dateRange: `${startDate} - ${endDate}`,
            generatedOn: new Date().toLocaleString('en-GB', { day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' }).replace(',', ''),
            generatedBy: "Super Admin",
            format: newReport.format
        };
        
        setReportsData([generatedReport, ...reportsData]);
        setShowModal(false);
        setNewReport({ name: '', category: 'Institute Reports', type: 'Summary', format: 'PDF' });
        toast.success("Custom Report generated!");
    };
    
    // Realistic mock data as per the implementation plan
    const [reportsData, setReportsData] = useState([
        {
            id: 1,
            name: "Monthly Revenue Report",
            desc: "Revenue analysis for all institutes",
            icon: <FiFileText />,
            iconClass: "icon-purple",
            category: "Revenue Reports",
            catBadge: "orange",
            type: "Summary",
            dateRange: "01 Aug - 31 Aug 2026",
            generatedOn: "31 Aug 2026 10:30 AM",
            generatedBy: "Super Admin",
            format: "PDF"
        },
        {
            id: 2,
            name: "Institute Performance Report",
            desc: "Overall performance of all institutes",
            icon: <BiBuildingHouse />,
            iconClass: "icon-green",
            category: "Institute Reports",
            catBadge: "purple",
            type: "Detailed",
            dateRange: "01 Aug - 31 Aug 2026",
            generatedOn: "31 Aug 2026 09:15 AM",
            generatedBy: "Super Admin",
            format: "Excel"
        },
        {
            id: 3,
            name: "User Activity Report",
            desc: "User registration and activity summary",
            icon: <FiUsers />,
            iconClass: "icon-blue",
            category: "User Reports",
            catBadge: "green",
            type: "Summary",
            dateRange: "01 Aug - 31 Aug 2026",
            generatedOn: "30 Aug 2026 06:45 PM",
            generatedBy: "Super Admin",
            format: "PDF"
        },
        {
            id: 4,
            name: "Subscription Status Report",
            desc: "Active and expired subscriptions",
            icon: <FiCreditCard />,
            iconClass: "icon-orange",
            category: "Subscription Reports",
            catBadge: "blue",
            type: "Detailed",
            dateRange: "01 Aug - 31 Aug 2026",
            generatedOn: "30 Aug 2026 03:20 PM",
            generatedBy: "Super Admin",
            format: "Excel"
        },
        {
            id: 5,
            name: "System Activity Report",
            desc: "Platform usage and system logs",
            icon: <FiServer />,
            iconClass: "icon-red",
            category: "System Reports",
            catBadge: "red",
            type: "Summary",
            dateRange: "29 Aug - 31 Aug 2026",
            generatedOn: "31 Aug 2026 11:00 AM",
            generatedBy: "Super Admin",
            format: "PDF"
        }
    ]);

    return (
        <div className="sm-reports-container">
            <div className="sm-reports-header">
                <div className="sm-reports-header-left">
                    <div className="sm-reports-icon-wrap">
                        <FiFileText />
                    </div>
                    <div className="sm-reports-header-text">
                        <h1>Reports</h1>
                        <p>Generate and view detailed reports across the platform.</p>
                    </div>
                </div>
                <div className="sm-reports-header-right">
                    <div className="sm-reports-date-btn" style={{ padding: '0.25rem 0.5rem' }}>
                        <input type="date" value={startDate} onChange={e => setStartDate(e.target.value)} style={{border:'none', background:'transparent', outline:'none', color:'inherit', fontFamily:'inherit'}} />
                        <span style={{margin: '0 4px'}}>-</span>
                        <input type="date" value={endDate} onChange={e => setEndDate(e.target.value)} style={{border:'none', background:'transparent', outline:'none', color:'inherit', fontFamily:'inherit'}} />
                    </div>
                    <button className="sm-reports-generate-btn" onClick={() => setShowModal(true)}>
                        <FiPlus /> Generate Custom Report
                    </button>
                    <ThemeSelector />
                </div>
            </div>

            {/* KPIs Grid */}
            <div className="sm-reports-kpi-grid">
                <div className="sm-reports-kpi-card">
                    <div className="sm-kpi-icon icon-purple"><FiCalendar /></div>
                    <div className="sm-kpi-content">
                        <span className="sm-kpi-title">Total Reports</span>
                        <span className="sm-kpi-value">24</span>
                        <span className="sm-kpi-trend up">↑ 14.3% vs last month</span>
                    </div>
                </div>
                <div className="sm-reports-kpi-card">
                    <div className="sm-kpi-icon icon-green"><FiActivity /></div>
                    <div className="sm-kpi-content">
                        <span className="sm-kpi-title">Generated This Month</span>
                        <span className="sm-kpi-value">8</span>
                        <span className="sm-kpi-trend up">↑ 33.3% vs last month</span>
                    </div>
                </div>
                <div className="sm-reports-kpi-card">
                    <div className="sm-kpi-icon icon-blue"><FiDownload /></div>
                    <div className="sm-kpi-content">
                        <span className="sm-kpi-title">Downloaded Reports</span>
                        <span className="sm-kpi-value">16</span>
                        <span className="sm-kpi-trend up">↑ 20.0% vs last month</span>
                    </div>
                </div>
                <div className="sm-reports-kpi-card">
                    <div className="sm-kpi-icon icon-red"><FiClock /></div>
                    <div className="sm-kpi-content">
                        <span className="sm-kpi-title">Scheduled Reports</span>
                        <span className="sm-kpi-value">4</span>
                        <span className="sm-kpi-trend down">↓ 11.1% vs last month</span>
                    </div>
                </div>
                <div className="sm-reports-kpi-card">
                    <div className="sm-kpi-icon icon-orange"><FiSettings /></div>
                    <div className="sm-kpi-content">
                        <span className="sm-kpi-title">Custom Reports</span>
                        <span className="sm-kpi-value">6</span>
                        <span className="sm-kpi-trend up">↑ 25.0% vs last month</span>
                    </div>
                </div>
            </div>

            {/* Categories */}
            <h2 className="sm-section-title">Report Categories</h2>
            <div className="sm-reports-cat-grid">
                <div className="sm-cat-card">
                    <div className="sm-cat-header">
                        <div className="sm-cat-icon icon-purple"><BiBuildingHouse /></div>
                        <div className="sm-cat-info">
                            <h3>Institute Reports</h3>
                            <p>Performance and activity reports for all institutes</p>
                        </div>
                    </div>
                    <div className="sm-cat-footer">
                        <span>6 Reports</span>
                        <FiArrowRight />
                    </div>
                </div>
                
                <div className="sm-cat-card">
                    <div className="sm-cat-header">
                        <div className="sm-cat-icon icon-green"><FiUsers /></div>
                        <div className="sm-cat-info">
                            <h3>User Reports</h3>
                            <p>User registration and activity analytics</p>
                        </div>
                    </div>
                    <div className="sm-cat-footer">
                        <span>5 Reports</span>
                        <FiArrowRight />
                    </div>
                </div>
                
                <div className="sm-cat-card">
                    <div className="sm-cat-header">
                        <div className="sm-cat-icon icon-orange"><FiCreditCard /></div>
                        <div className="sm-cat-info">
                            <h3>Revenue Reports</h3>
                            <p>Financial performance and revenue analysis</p>
                        </div>
                    </div>
                    <div className="sm-cat-footer">
                        <span>4 Reports</span>
                        <FiArrowRight />
                    </div>
                </div>
                
                <div className="sm-cat-card">
                    <div className="sm-cat-header">
                        <div className="sm-cat-icon icon-blue"><FiFileText /></div>
                        <div className="sm-cat-info">
                            <h3>Subscription Reports</h3>
                            <p>Subscription status and billing reports</p>
                        </div>
                    </div>
                    <div className="sm-cat-footer">
                        <span>4 Reports</span>
                        <FiArrowRight />
                    </div>
                </div>
                
                <div className="sm-cat-card">
                    <div className="sm-cat-header">
                        <div className="sm-cat-icon icon-purple"><FiSettings /></div>
                        <div className="sm-cat-info">
                            <h3>System Reports</h3>
                            <p>System logs and platform usage reports</p>
                        </div>
                    </div>
                    <div className="sm-cat-footer">
                        <span>5 Reports</span>
                        <FiArrowRight />
                    </div>
                </div>
            </div>

            {/* Recent Reports Table */}
            <h2 className="sm-section-title">Recent Reports</h2>
            <div className="sm-reports-table-container">
                <table className="sm-reports-table">
                    <thead>
                        <tr>
                            <th>Report Name</th>
                            <th>Category</th>
                            <th>Type</th>
                            <th>Date Range</th>
                            <th>Generated On</th>
                            <th>Generated By</th>
                            <th>Format</th>
                            <th style={{ textAlign: 'center' }}>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        {reportsData.map(report => (
                            <tr key={report.id}>
                                <td>
                                    <div className="sm-rep-name-cell">
                                        <div className={`sm-rep-name-icon ${report.iconClass}`}>
                                            {report.icon}
                                        </div>
                                        <div className="sm-rep-name-info">
                                            <strong>{report.name}</strong>
                                            <span>{report.desc}</span>
                                        </div>
                                    </div>
                                </td>
                                <td>
                                    <span className={`sm-badge ${report.catBadge}`}>{report.category}</span>
                                </td>
                                <td>{report.type}</td>
                                <td>{report.dateRange}</td>
                                <td>
                                    <div className="sm-rep-name-info">
                                        <span>{report.generatedOn.split(' ')[0] + ' ' + report.generatedOn.split(' ')[1] + ' ' + report.generatedOn.split(' ')[2]}</span>
                                        <span>{report.generatedOn.split(' ')[3] + ' ' + report.generatedOn.split(' ')[4]}</span>
                                    </div>
                                </td>
                                <td>{report.generatedBy}</td>
                                <td>
                                    <span className={`sm-format-badge ${report.format.toLowerCase()}`}>{report.format}</span>
                                </td>
                                <td>
                                    <div className="sm-rep-actions" style={{ justifyContent: 'center', position: 'relative' }}>
                                        <button className="sm-rep-action-btn" title="Download" onClick={() => handleDownload(report)}>
                                            <FiDownload />
                                        </button>
                                        <button className="sm-rep-action-btn" title="More options" onClick={() => setActionMenuOpen(actionMenuOpen === report.id ? null : report.id)}>
                                            <FiMoreVertical />
                                        </button>
                                        
                                        {actionMenuOpen === report.id && (
                                            <div ref={menuRef} style={{
                                                position: 'absolute', right: '0', top: '100%', zIndex: 10,
                                                background: 'var(--sal-card-bg, #fff)', border: '1px solid var(--sal-border, #e2e8f0)',
                                                borderRadius: '8px', boxShadow: '0 4px 6px -1px rgba(0,0,0,0.1)',
                                                padding: '0.5rem', minWidth: '120px', display: 'flex', flexDirection: 'column', gap: '0.25rem'
                                            }}>
                                                <button onClick={() => {toast.success("Report scheduled"); setActionMenuOpen(null)}} style={{
                                                    background:'none', border:'none', padding:'0.5rem', textAlign:'left', borderRadius:'4px', cursor:'pointer', color:'var(--sal-sidebar-text, #1e293b)'
                                                }}>Schedule</button>
                                                <button onClick={() => {toast.success("Report deleted"); setReportsData(reportsData.filter(r => r.id !== report.id)); setActionMenuOpen(null)}} style={{
                                                    background:'none', border:'none', padding:'0.5rem', textAlign:'left', borderRadius:'4px', cursor:'pointer', color:'#ef4444'
                                                }}>Delete</button>
                                            </div>
                                        )}
                                    </div>
                                </td>
                            </tr>
                        ))}
                    </tbody>
                </table>
                <div className="sm-pagination">
                    <div className="sm-page-info">
                        Showing 1 to 5 of 24 results
                    </div>
                    <div className="sm-page-controls">
                        <button className="sm-page-btn">&lt;</button>
                        <button className="sm-page-btn active">1</button>
                        <button className="sm-page-btn">2</button>
                        <button className="sm-page-btn">3</button>
                        <button className="sm-page-btn" style={{pointerEvents:'none'}}>...</button>
                        <button className="sm-page-btn">5</button>
                        <button className="sm-page-btn">&gt;</button>
                    </div>
                </div>
            </div>
            
            {/* Generate Report Modal */}
            {showModal && (
                <div style={{
                    position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, 
                    backgroundColor: 'rgba(0,0,0,0.5)', zIndex: 999, display: 'flex', 
                    alignItems: 'center', justifyContent: 'center'
                }}>
                    <div style={{
                        background: 'var(--sal-card-bg, #fff)', color: 'var(--sal-sidebar-text, #1e293b)',
                        padding: '2rem', borderRadius: '12px', width: '100%', maxWidth: '400px',
                        boxShadow: '0 20px 25px -5px rgba(0,0,0,0.1), 0 10px 10px -5px rgba(0,0,0,0.04)'
                    }}>
                        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.5rem' }}>
                            <h2 style={{ margin: 0, fontSize: '1.25rem', fontWeight: 600 }}>Generate Custom Report</h2>
                            <button onClick={() => setShowModal(false)} style={{ background: 'none', border: 'none', fontSize: '1.25rem', cursor: 'pointer', color: 'inherit' }}><FiX /></button>
                        </div>
                        
                        <form onSubmit={handleGenerate} style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
                            <div>
                                <label style={{ display: 'block', marginBottom: '0.25rem', fontSize: '0.875rem', fontWeight: 500 }}>Report Name</label>
                                <input type="text" required value={newReport.name} onChange={e => setNewReport({...newReport, name: e.target.value})} style={{
                                    width: '100%', padding: '0.5rem', borderRadius: '6px', border: '1px solid var(--sal-border, #e2e8f0)', background: 'transparent', color: 'inherit'
                                }} placeholder="e.g. Q3 Analytics Summary" />
                            </div>
                            
                            <div>
                                <label style={{ display: 'block', marginBottom: '0.25rem', fontSize: '0.875rem', fontWeight: 500 }}>Category</label>
                                <select value={newReport.category} onChange={e => setNewReport({...newReport, category: e.target.value})} style={{
                                    width: '100%', padding: '0.5rem', borderRadius: '6px', border: '1px solid var(--sal-border, #e2e8f0)', background: 'var(--sal-bg, #f8fafc)', color: 'inherit'
                                }}>
                                    <option>Institute Reports</option>
                                    <option>User Reports</option>
                                    <option>Revenue Reports</option>
                                    <option>Subscription Reports</option>
                                    <option>System Reports</option>
                                </select>
                            </div>
                            
                            <div style={{ display: 'flex', gap: '1rem' }}>
                                <div style={{ flex: 1 }}>
                                    <label style={{ display: 'block', marginBottom: '0.25rem', fontSize: '0.875rem', fontWeight: 500 }}>Type</label>
                                    <select value={newReport.type} onChange={e => setNewReport({...newReport, type: e.target.value})} style={{
                                        width: '100%', padding: '0.5rem', borderRadius: '6px', border: '1px solid var(--sal-border, #e2e8f0)', background: 'var(--sal-bg, #f8fafc)', color: 'inherit'
                                    }}>
                                        <option>Summary</option>
                                        <option>Detailed</option>
                                    </select>
                                </div>
                                <div style={{ flex: 1 }}>
                                    <label style={{ display: 'block', marginBottom: '0.25rem', fontSize: '0.875rem', fontWeight: 500 }}>Format</label>
                                    <select value={newReport.format} onChange={e => setNewReport({...newReport, format: e.target.value})} style={{
                                        width: '100%', padding: '0.5rem', borderRadius: '6px', border: '1px solid var(--sal-border, #e2e8f0)', background: 'var(--sal-bg, #f8fafc)', color: 'inherit'
                                    }}>
                                        <option>PDF</option>
                                        <option>Excel</option>
                                    </select>
                                </div>
                            </div>
                            
                            <button type="submit" className="sm-reports-generate-btn" style={{ width: '100%', justifyContent: 'center', marginTop: '1rem', padding: '0.75rem' }}>
                                Generate Now
                            </button>
                        </form>
                    </div>
                </div>
            )}
            
        </div>
    );
}

export default Reports;
